### ISSUE TITLE
VTK not found for Python 3.7.3

### ISSUE THREAD

**Issue by cbedetti** [scilus/scilpy#45] opened 2019-09-05 16:05 UTC
`pip install -r requirements.txt` is not working under Python 3.7.3 (fresh venv)

```
Collecting vtk==8.1.0 (from -r requirements.txt (line 18))
  Could not find a version that satisfies the requirement vtk==8.1.0 (from -r requirements.txt (line 18)) (from versions: 8.1.2)
No matching distribution found for vtk==8.1.0 (from -r requirements.txt (line 18))
```

**Comment by GuillaumeTh** [comment] 2019-09-10 15:28
Hi @cbedetti.
That's because Python 3.7 support only vtk 8.1.2. We didn't test the scripts with this new vtk version.

**Comment by cbedetti** [comment] 2019-09-10 19:25
No problem
Just want to let you know :+1:

**Comment by jchoude** [comment] 2019-10-04 01:21
@GuillaumeTh can we either update to use 8.1.2, or change the requirements to >=8.1.0? This way it would also work for those versions of Python.

This would probably not change anything for reproducibility, since we don't test those things for visu right now.

**Comment by GuillaumeTh** [comment] 2019-10-10 19:29
@jchoude Yes, I will update the requirements.

**Comment by jchoude** [comment] 2020-03-09 15:43
So, PR #74 was closed without resolution. I know that we mainly pull this dependency from Fury. How do you want to handle it @GuillaumeTh ?

**Comment by arnaudbore** [comment] 2020-04-02 22:17
Has been fixed in #168

**Closed by arnaudbore** 2020-04-02 22:17 UTC
